### ISSUE TITLE
Got Rid of My HUD!

### ISSUE THREAD

**Issue by LevenLMR** [henkelmax/camera#68]
I used the camera and my HUD disappeared completely and i can't get ut back.

**Comment by azeman** [comment]
Hi, I had the same issue alongside 103 other mods (1.12.2, macOS Sonoma). The issue only occurs with Optifine :
- the game loads without any HUD when using a shader (even the internal shader).
- the game doesn't load at all and is stuck on the dirt screen when not using a shader.
- 
Conclusion: since devs appear not to be interested in fixing this bug, proceed to move camera-1.0.11.jar into the recycle bin, and forget about it.
